import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@foundation/ui/src/index.css'
import { Container } from '@foundation/ui/src/components/atoms/container'
import { Footer } from '@foundation/ui/src/components/organisms/Footer'
import { Navbar } from '@foundation/ui/src/components/organisms/Navbar'
import { SessionProvider } from '@foundation/ui/src/components/molecules/SessionProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <SessionProvider>
            <Navbar />
            {children}
          </SessionProvider>
        </Container>
        <Footer />
      </body>
    </html>
  )
}
